### ISSUE TITLE
errors when extracting win package

### ISSUE THREAD

**Issue by epasho** [Arachni/build-scripts-windows#1]
I was able to extract with errors and UI runs but not sure if this errors are a big issue. 
![capture1](https://cloud.githubusercontent.com/assets/5025702/11212710/67a5592a-8d05-11e5-9cb3-3aaf556c76e5.PNG)

Also, the HTml export zip is emply when i try to download the report.

**Comment by Zapotek** [comment]
I can't rproduce it, although those files aren't important and won't be included in the final release.
About the HTML report, are there any errors printed in the WebUI terminal or in the logfiles under `system/logs/`?

**Comment by epasho** [comment]
i get invalid file when i try to unzip it. i looked at the logs but nothing that would tell something

**Comment by Zapotek** [comment]
Good catch, it's a Windows only thing when creating the zip archive.

**Comment by Zapotek** [comment]
Windows nightly is up, should work fine now.

Cheers

**Comment by epasho** [comment]
It's fine now. Thanks.
Any reasons that you have moved the reports as zip files instead of links / part of the scann tool? It was more convinient before.

**Comment by Zapotek** [comment]
It was never "part" of it, it just so happened that the report used to be a single file so the browser opened it immediately.
This report contains more asset files and having all of them dumped into the HTML would have been unworkable for many reasons (caching, font files, etc.).
